dataset_path: louis-mart/GMAI-MMBench-val

task: "gmai"
dataset_kwargs:
  token: True
test_split: validation
output_type: generate_until
doc_to_visual: !function utils.gmai_doc_to_visual
doc_to_text: !function utils.gmai_doc_to_text
doc_to_target: "answer"
process_results: !function utils.gmai_process_results
  
lmms_eval_specific_kwargs:
  default:
    pre_prompt: ""
    post_prompt: "Let's think step by step. Detail your reasoning before answering carefully. Your answer should have the following format: <reasoning leading to the answer> Answer: <letter> The <letter> is chosen amongst the possible options (A, B, C, D or E)"


generation_kwargs:
  max_new_tokens: 2048
  temperature: 0
  do_sample: False


metric_list:
  - metric: accuracy
    aggregation: !function utils.gmai_aggregate_results 
    higher_is_better: true

metadata:
  - version: 0.0
