dataset_path: flaviagiammarino/path-vqa

task: "path_vqa"

dataset_kwargs:
  token: True
test_split: test

output_type: generate_until

doc_to_visual: !function utils.pathvqa_doc_to_visual
doc_to_text: !function utils.pathvqa_doc_to_text
doc_to_target: !function utils.pathvqa_doc_to_target

generation_kwargs:
  max_new_tokens: 64
  do_sample: False

metric_list:
  - metric: accuracy
    aggregation: !function utils.pathvqa_aggregate_results
    higher_is_better: true

process_results: !function utils.pathvqa_process_results

metadata:
  - version: 0.0

lmms_eval_specific_kwargs:
  default:
    pre_prompt: ""
    post_prompt: "Answer with a single short word or phrase only (no punctuation, no explanation). If the answer is affirmative, reply 'Yes'; if negative, reply 'No'."
